Repository CodeMedics/Harulog-backend, pull requests merged in 2023-08, with the labels that each got.

#21 [Feat] Config, jwt 구성
  src/main/java/com/ohgiraffers/dailylogbackend/configuration/JwtSecurityConfig.java
  src/main/java/com/ohgiraffers/dailylogbackend/configuration/SecurityConfig.java
  src/main/java/com/ohgiraffers/dailylogbackend/configuration/WebConfig.java
  src/main/java/com/ohgiraffers/dailylogbackend/declaration/command/domain/aggregate/entity/Report.java
  src/main/java/com/ohgiraffers/dailylogbackend/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/ohgiraffers/dailylogbackend/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/ohgiraffers/dailylogbackend/jwt/JwtFilter.java
  src/main/java/com/ohgiraffers/dailylogbackend/jwt/TokenProvider.java
  src/main/java/com/ohgiraffers/dailylogbackend/login/controller/LoginController.java
  src/main/java/com/ohgiraffers/dailylogbackend/login/dto/AccessTokenDTO.java
  src/main/java/com/ohgiraffers/dailylogbackend/login/repository/LoginRepository.java
  src/main/java/com/ohgiraffers/dailylogbackend/login/service/LoginService.java
  src/main/java/com/ohgiraffers/dailylogbackend/member/command/domain/aggregate/entity/Member.java
  src/test/java/com/ohgiraffers/dailylogbackend/member/MemberTests.java
Labels: 서류, 처리중

#19 [Feat] 좋아요 Repository, Service 구현
  src/main/java/com/ohgiraffers/dailylogbackend/like/command/infra/repository/LikesRepository.java
  src/main/java/com/ohgiraffers/dailylogbackend/like/command/infra/repository/Repository.java
  src/main/java/com/ohgiraffers/dailylogbackend/like/command/infra/service/LikesService.java
  src/main/java/com/ohgiraffers/dailylogbackend/like/command/infra/service/Service.java
Labels: 기능, 처리중

#18 [Feat] 신고
  src/main/java/com/ohgiraffers/dailylogbackend/common/AuditingFields.java
  src/main/java/com/ohgiraffers/dailylogbackend/declaration/command/domain/aggregate/entity/Report.java
Labels: 기능

#30 [Build] application.yml
  build.gradle
  src/main/resources/application.yml
Labels: 요청

#34 신고 엔티티 수정 및 Enum, DTO 구현
  src/main/java/com/ohgiraffers/dailylogbackend/comment/command/domain/aggregate/entity/CommentEntity.java
  src/main/java/com/ohgiraffers/dailylogbackend/file/command/domain/aggregate/entity/FileEntity.java
  src/main/java/com/ohgiraffers/dailylogbackend/like/command/infra/repository/LikesRepository.java
  src/main/java/com/ohgiraffers/dailylogbackend/report/command/application/dto/reportDTO.java
  src/main/java/com/ohgiraffers/dailylogbackend/report/command/domain/aggregate/EnumType/ReportStateEnum.java
  src/main/java/com/ohgiraffers/dailylogbackend/report/command/domain/aggregate/EnumType/ReportTypeEnum.java
  src/main/java/com/ohgiraffers/dailylogbackend/report/command/domain/aggregate/entity/ReportEntity.java
Labels: 서류, 기능

#60 일기 테스트 코드 작성 완료(Issue # 43)
  .github/workflows/develop-gradle.yml
  src/main/java/com/ohgiraffers/dailylogbackend/Application.java
  src/main/java/com/ohgiraffers/dailylogbackend/configuration/JPAConfiguration.java
  src/main/java/com/ohgiraffers/dailylogbackend/configuration/WebConfig.java
  src/main/java/com/ohgiraffers/dailylogbackend/diary/command/application/dto/DiaryDTO.java
  src/main/java/com/ohgiraffers/dailylogbackend/diary/command/application/dto/DiaryUpdateDTO.java
  src/main/java/com/ohgiraffers/dailylogbackend/diary/command/application/dto/DiaryWriteDTO.java
  src/main/java/com/ohgiraffers/dailylogbackend/diary/command/application/service/DiaryService.java
  src/main/java/com/ohgiraffers/dailylogbackend/diary/command/application/service/Service.java
  src/main/java/com/ohgiraffers/dailylogbackend/diary/command/domain/aggregate/entity/DiaryEntity.java
  src/main/java/com/ohgiraffers/dailylogbackend/diary/command/domain/service/Service.java
  src/main/java/com/ohgiraffers/dailylogbackend/diary/command/infra/repository/Repository.java
  src/main/java/com/ohgiraffers/dailylogbackend/diary/command/infra/service/DiaryService.java
  src/main/java/com/ohgiraffers/dailylogbackend/file/command/domain/aggregate/entity/FileEntity.java
  src/main/java/com/ohgiraffers/dailylogbackend/jwt/TokenProvider.java
  src/main/java/com/ohgiraffers/dailylogbackend/like/command/infra/repository/LikesRepository.java
  src/main/java/com/ohgiraffers/dailylogbackend/login/repository/LoginRepository.java
  src/main/java/com/ohgiraffers/dailylogbackend/member/command/application/dto/CreateMemberDTO.java
  src/main/java/com/ohgiraffers/dailylogbackend/member/command/application/service/CreateMemberService.java
  src/main/java/com/ohgiraffers/dailylogbackend/member/command/application/service/Service.java
  src/main/java/com/ohgiraffers/dailylogbackend/member/command/domain/aggregate/entity/MemberEntity.java
  src/main/java/com/ohgiraffers/dailylogbackend/member/command/domain/aggregate/vo/Vo.java
  src/main/java/com/ohgiraffers/dailylogbackend/member/command/domain/repository/MemberRepository.java
  src/main/java/com/ohgiraffers/dailylogbackend/report/command/domain/aggregate/entity/ReportEntity.java
  src/main/resources/application.yml
  src/test/java/com/ohgiraffers/dailylogbackend/ApplicationTests.java
  src/test/java/com/ohgiraffers/dailylogbackend/diary/DiaryTest.java
  src/test/java/com/ohgiraffers/dailylogbackend/diary/InsertFakeUser.java
  src/test/java/com/ohgiraffers/dailylogbackend/diary/initial/DiaryDeleteTest.java
  src/test/java/com/ohgiraffers/dailylogbackend/diary/initial/DiaryUpdateTest.java
  src/test/java/com/ohgiraffers/dailylogbackend/diary/initial/DiaryWriteMockTest.java
  src/test/java/com/ohgiraffers/dailylogbackend/diary/initial/DiaryWriteTest.java
Labels: 기능

#65 (#63) 피드 관련 사항 기초 구현
  src/main/java/com/ohgiraffers/dailylogbackend/feed/command/application/service/FeedService.java
  src/main/java/com/ohgiraffers/dailylogbackend/feed/command/application/service/Service.java
  src/main/java/com/ohgiraffers/dailylogbackend/feed/command/domain/aggregate/entity/Entity.java
  src/main/java/com/ohgiraffers/dailylogbackend/feed/command/domain/aggregate/entity/FeedEntity.java
  src/main/java/com/ohgiraffers/dailylogbackend/feed/command/domain/service/Service.java
  src/main/java/com/ohgiraffers/dailylogbackend/feed/command/infra/repository/FeedRepository.java
  src/main/java/com/ohgiraffers/dailylogbackend/feed/command/infra/repository/Repository.java
  src/main/java/com/ohgiraffers/dailylogbackend/feed/command/infra/service/Service.java
  src/main/java/com/ohgiraffers/dailylogbackend/feed/query/application/Application.java
  src/main/java/com/ohgiraffers/dailylogbackend/feed/query/application/service/GetFeedService.java
  src/main/java/com/ohgiraffers/dailylogbackend/feed/query/infra/Infra.java
  src/main/java/com/ohgiraffers/dailylogbackend/feed/query/infra/mapper/GetFeedMapper.java
  src/main/resources/mapper/feed/FeedMapper.xml
  src/test/java/com/ohgiraffers/dailylogbackend/diary/DiaryTest.java
Labels: 요청

#69 Feature/file feature
  .gitignore
  build.gradle
  src/main/java/com/ohgiraffers/dailylogbackend/Application.java
  src/main/java/com/ohgiraffers/dailylogbackend/file/command/application/controller/Controller.java
  src/main/java/com/ohgiraffers/dailylogbackend/file/command/application/controller/FileController.java
  src/main/java/com/ohgiraffers/dailylogbackend/file/command/domain/service/FileServiceImpl.java
  src/main/java/com/ohgiraffers/dailylogbackend/file/command/infra/repository/FileRepository.java
  src/main/java/com/ohgiraffers/dailylogbackend/like/command/infra/service/LikesService.java
  src/test/java/com/ohgiraffers/dailylogbackend/file/FileServiceTests.java
  src/testImg/harulog.jpg
  src/testImg/kim.jpg
  src/testImg/nam.jpg
Labels: 테스트

#87 [#73] 댓글 Entity 리팩토링
  src/main/java/com/ohgiraffers/dailylogbackend/comment/command/application/dto/CommentSaveDTO.java
  src/main/java/com/ohgiraffers/dailylogbackend/comment/command/application/dto/CommentUpdateDTO.java
  src/main/java/com/ohgiraffers/dailylogbackend/comment/command/application/dto/DTO.java
  src/main/java/com/ohgiraffers/dailylogbackend/comment/command/domain/aggregate/entity/CommentEntity.java
  src/main/java/com/ohgiraffers/dailylogbackend/comment/command/domain/aggregate/vo/CommentDiaryVO.java
  src/main/java/com/ohgiraffers/dailylogbackend/comment/command/domain/aggregate/vo/CommentMemberVO.java
  src/main/java/com/ohgiraffers/dailylogbackend/comment/command/domain/aggregate/vo/Vo.java
Labels: 리팩토링

#88 [#73] CommentMemberVO, CommentSaveDTO 리팩토링
  src/main/java/com/ohgiraffers/dailylogbackend/comment/command/application/dto/CommentSaveDTO.java
  src/main/java/com/ohgiraffers/dailylogbackend/comment/command/domain/aggregate/vo/CommentMemberVO.java
Labels: 리팩토링

#92 [refactoring] DiaryEntity, CommentEntity
  src/main/java/com/ohgiraffers/dailylogbackend/comment/command/domain/aggregate/entity/CommentEntity.java
  src/main/java/com/ohgiraffers/dailylogbackend/comment/command/domain/aggregate/vo/CommentDiaryVO.java
  src/main/java/com/ohgiraffers/dailylogbackend/diary/command/domain/aggregate/entity/DiaryEntity.java
Labels: 리팩토링
